// K-Quest & Velorah® TOPIK 1-6 Expanded Database
// Contains exactly 300 essential words (50 words per level) with Mongolian translations, romanized pronunciations, POS, and examples.

const KQUEST_WORDS = [
  // ================= LEVEL 1 (1 - 50) =================
  { id: 1, level: 1, word: "가다", pronunciation: "gada", meaning: "явах", pos: "Үйл үг", exampleKo: "학교에 갑니다.", exampleMn: "Сургуульд явна." },
  { id: 2, level: 1, word: "오다", pronunciation: "oda", meaning: "ирэх", pos: "Үйл үг", exampleKo: "친구가 집에 옵니다.", exampleMn: "Найз гэрт ирж байна." },
  { id: 3, level: 1, word: "먹다", pronunciation: "meokda", meaning: "идэх", pos: "Үйл үг", exampleKo: "사과를 먹어요.", exampleMn: "Алим иддэг." },
  { id: 4, level: 1, word: "마시다", pronunciation: "masida", meaning: "уух", pos: "Үйл үг", exampleKo: "물을 마십니다.", exampleMn: "Ус ууж байна." },
  { id: 5, level: 1, word: "보다", pronunciation: "boda", meaning: "харах", pos: "Үйл үг", exampleKo: "영화가 보고 싶어요.", exampleMn: "Кино үзэхийг хүсэж байна." },
  { id: 6, level: 1, word: "듣다", pronunciation: "deutda", meaning: "сонсох", pos: "Үйл үг", exampleKo: "음악을 듣습니다.", exampleMn: "Хөгжим сонсдог." },
  { id: 7, level: 1, word: "읽다", pronunciation: "ilgda", meaning: "унших", pos: "Үйл үг", exampleKo: "책을 읽어요.", exampleMn: "Ном уншдаг." },
  { id: 8, level: 1, word: "쓰다", pronunciation: "sseuda", meaning: "бичих", pos: "Үйл үг", exampleKo: "편지를 씁니다.", exampleMn: "Захидал бичиж байна." },
  { id: 9, level: 1, word: "자다", pronunciation: "jada", meaning: "унтах", pos: "Үйл үг", exampleKo: "아기가 침대에서 자요.", exampleMn: "Хүүхэд орон дээр унтаж байна." },
  { id: 10, level: 1, word: "일어나다", pronunciation: "ireonada", meaning: "босох", pos: "Үйл үг", exampleKo: "아침 6시에 일어납니다.", exampleMn: "Өглөө 6 цагт босдог." },
  { id: 11, level: 1, word: "공부하다", pronunciation: "gongbuhada", meaning: "сурах", pos: "Үйл үг", exampleKo: "매일 한국어를 공부해요.", exampleMn: "Өдөр бүр солонгос хэл сурдаг." },
  { id: 12, level: 1, word: "일하다", pronunciation: "ilhada", meaning: "ажиллах", pos: "Үйл үг", exampleKo: "아버지는 회사에서 일하십니다.", exampleMn: "Аав компанид ажилладаг." },
  { id: 13, level: 1, word: "좋아하다", pronunciation: "johahada", meaning: "дуртай байх", pos: "Үйл үг", exampleKo: "저는 우유를 좋아합니다.", exampleMn: "Би сүүнд дуртай." },
  { id: 14, level: 1, word: "싫어하다", pronunciation: "silheohada", meaning: "дургүй байх", pos: "Үйл үг", exampleKo: "야채를 정말 싫어해요.", footprint: "", exampleMn: "Хүнсний ногоонд үнэхээр дургүй." },
  { id: 15, level: 1, word: "사다", pronunciation: "sada", meaning: "худалдаж авах", pos: "Үйл үг", exampleKo: "가방을 샀어요.", exampleMn: "Цүнх худалдаж авсан." },
  { id: 16, level: 1, word: "팔다", pronunciation: "palda", meaning: "зарах", pos: "Үйл үг", exampleKo: "시장에서 옷을 팝니다.", exampleMn: "Зах дээр хувцас зардаг." },
  { id: 17, level: 1, word: "만나다", pronunciation: "mannada", meaning: "уулзах", pos: "Үйл үг", exampleKo: "오늘 친구를 만나요.", exampleMn: "Өнөөдөр найзтайгаа уулзаж байна." },
  { id: 18, level: 1, word: "살다", pronunciation: "salda", meaning: "амьдрах", pos: "Үйл үг", exampleKo: "가족과 울란바토르에 삽니다.", exampleMn: "Гэр бүлтэйгээ Улаанбаатарт амьдардаг." },
  { id: 19, level: 1, word: "배우다", pronunciation: "baeuda", meaning: "сурах", pos: "Үйл үг", exampleKo: "요리를 배우고 있어요.", exampleMn: "Хоол хийхийг сурч байна." },
  { id: 20, level: 1, word: "쉬다", pronunciation: "swida", meaning: "амрах", pos: "Үйл үг", exampleKo: "집에서 푹 쉽니다.", exampleMn: "Гэртээ сайн амардаг." },
  { id: 21, level: 1, word: "학교", pronunciation: "hakgyo", meaning: "сургууль", pos: "Нэр үг", exampleKo: "학교가 참 아름답습니다.", exampleMn: "Сургууль үнэхээр үзэсгэлэнтэй байна." },
  { id: 22, level: 1, word: "친구", pronunciation: "chingu", meaning: "найз", pos: "Нэр үг", exampleKo: "좋은 친구가 최고입니다.", exampleMn: "Сайн найз хамгийн шилдэг нь." },
  { id: 23, level: 1, word: "가족", pronunciation: "gajok", meaning: "гэр бүл", pos: "Нэр үг", exampleKo: "우리 가족은 4명입니다.", exampleMn: "Манай гэр бүл 4 гишүүнтэй." },
  { id: 24, level: 1, word: "어머니", pronunciation: "eomeoni", meaning: "ээж", pos: "Нэр үг", exampleKo: "어머니 사랑합니다.", exampleMn: "Ээж ээ, тандаа хайртай." },
  { id: 25, level: 1, word: "아버지", pronunciation: "abeoji", meaning: "аав", pos: "Нэр үг", exampleKo: "아버지는 차가 있으십니다.", exampleMn: "Аав машинтай." },
  { id: 26, level: 1, word: "형/오빠", pronunciation: "hyeong/oppa", meaning: "ах", pos: "Нэр үг", exampleKo: "친형이 한 명 있어요.", exampleMn: "Төрсөн ах нэг байгаа." },
  { id: 27, level: 1, word: "언니/누나", pronunciation: "eonni/nuna", meaning: "эгч", pos: "Нэр үг", exampleKo: "언니는 대학생입니다.", exampleMn: "Эгч маань оюутан." },
  { id: 28, level: 1, word: "집", pronunciation: "jip", meaning: "гэр", pos: "Нэр үг", exampleKo: "우리 집은 따뜻해요.", exampleMn: "Манай гэр дулаахан." },
  { id: 29, level: 1, word: "방", pronunciation: "bang", meaning: "өрөө", pos: "Нэр үг", exampleKo: "내 방은 2층에 있습니다.", exampleMn: "Миний өрөө 2 давхарт байдаг." },
  { id: 30, level: 1, word: "음식", pronunciation: "eumsik", meaning: "хоол", pos: "Нэр үг", exampleKo: "매운 음식을 잘 먹어요.", exampleMn: "Халуун ногоотой хоолыг сайн иддэг." },
  { id: 31, level: 1, word: "물", pronunciation: "mul", meaning: "ус", pos: "Нэр үг", exampleKo: "물이 아주 깨끗합니다.", exampleMn: "Ус маш цэвэрхэн байна." },
  { id: 32, level: 1, word: "밥", pronunciation: "bap", meaning: "будаа/хоол", pos: "Нэр үг", exampleKo: "아침 밥을 꼭 드세요.", exampleMn: "Өглөөний хоолоо заавал идээрэй." },
  { id: 33, level: 1, word: "한국", pronunciation: "hanguk", meaning: "Солонгос", pos: "Нэр үг", exampleKo: "한국에 눈이 옵니다.", exampleMn: "Солонгост цас орж байна." },
  { id: 34, level: 1, word: "몽골", pronunciation: "monggol", meaning: "Монгол", pos: "Нэр үг", exampleKo: "몽골은 가을 날씨가 좋아요.", exampleMn: "Монголын намрын цаг агаар сайхан." },
  { id: 35, level: 1, word: "학생", pronunciation: "haksaeng", meaning: "сурагч", pos: "Нэр үг", exampleKo: "저는 몽골 고등학교 학생입니다.", exampleMn: "Би Монголын ахлах сургуулийн сурагч." },
  { id: 36, level: 1, word: "선생님", pronunciation: "seonsaengnim", meaning: "багш", pos: "Нэр үг", exampleKo: "선생님의 설명을 들었습니다.", exampleMn: "Багшийн тайлбарыг сонслоо." },
  { id: 37, level: 1, word: "시간", pronunciation: "sigan", meaning: "цаг", pos: "Нэр үг", exampleKo: "지금 약속 시간이 다 되었어요.", exampleMn: "Одоо уулзах цаг болчихлоо." },
  { id: 38, level: 1, word: "오늘", pronunciation: "oneul", meaning: "өнөөдөр", pos: "Нэр үг", exampleKo: "오늘은 날씨가 참 좋습니다.", exampleMn: "Өнөөдөр цаг агаар үнэхээр сайхан байна." },
  { id: 39, level: 1, word: "내일", pronunciation: "naeil", meaning: "маргааш", pos: "Нэр үг", exampleKo: "내일 아침에 전화할게요.", exampleMn: "Маргааш өглөө утасдъя." },
  { id: 40, level: 1, word: "어제", pronunciation: "eoje", meaning: "өчигдөр", pos: "Нэр үг", exampleKo: "어제 비가 많이 내렸어요.", exampleMn: "Өчигдөр бороо их орсон." },
  { id: 41, level: 1, word: "날씨", pronunciation: "nalssi", meaning: "цаг агаар", pos: "Нэр үг", exampleKo: "오늘 날씨가 춥습니다.", exampleMn: "Өнөөдөр цаг агаар хүйтэн байна." },
  { id: 42, level: 1, word: "비", pronunciation: "bi", meaning: "бороо", pos: "Нэр үг", exampleKo: "밖은 비가 오고 있어요.", exampleMn: "Гадаа бороо орж байна." },
  { id: 43, level: 1, word: "눈", pronunciation: "nun", meaning: "цас", pos: "Нэр үг", exampleKo: "눈이 하얗게 쌓였어요.", exampleMn: "Цас цав цагаан болон хуримтлагджээ." },
  { id: 44, level: 1, word: "사랑", pronunciation: "sarang", meaning: "хайр", pos: "Нэр үг", exampleKo: "부모님의 사랑은 끝이 없습니다.", exampleMn: "Аав ээжийн хайр хязгааргүй." },
  { id: 45, level: 1, word: "행복하다", pronunciation: "haengbokhada", meaning: "аз жаргалтай байх", pos: "Тэмдэг нэр", exampleKo: "매일 행복하게 사세요.", exampleMn: "Өдөр бүр аз жаргалтай амьдраарай." },
  { id: 46, level: 1, word: "슬프다", pronunciation: "seulpeuda", meaning: "гунигтай байх", pos: "Тэмдэг нэр", exampleKo: "영화가 너무 슬퍼요.", exampleMn: "Кино үнэхээр гунигтай байна." },
  { id: 47, level: 1, word: "예쁘다", pronunciation: "yeppeuda", meaning: "хөөрхөн", pos: "Тэмдэг нэр", exampleKo: "예쁜 꽃을 받았습니다.", exampleMn: "Хөөрхөн цэцэг бэлгэнд авлаа." },
  { id: 48, level: 1, word: "크다", pronunciation: "keuda", meaning: "том", pos: "Тэмдэг нэр", exampleKo: "집이 아주 큽니다.", exampleMn: "Гэр маш том юм." },
  { id: 49, level: 1, word: "작다", pronunciation: "jakda", meaning: "жижиг", pos: "Тэмдэг нэр", exampleKo: "이 신발은 작아서 안 맞아요.", exampleMn: "Энэ гутал жижигдээд таарахгүй байна." },
  { id: 50, level: 1, word: "많다", pronunciation: "manhta", meaning: "олон", pos: "Тэмдэг нэр", exampleKo: "교실에 학생이 많습니다.", exampleMn: "Ангид сурагч олон байна." },

  // ================= LEVEL 2 (51 - 100) =================
  { id: 51, level: 2, word: "기다리다", pronunciation: "gidarida", meaning: "хүлээх", pos: "Үйл үг", exampleKo: "여기서 버스를 기다려요.", exampleMn: "Энд автобус хүлээж байна." },
  { id: 52, level: 2, word: "준비하다", pronunciation: "junbihada", meaning: "бэлдэх", pos: "Үйл үг", exampleKo: "시험 공부를 준비해요.", exampleMn: "Шалгалтын бэлтгэл хийж байна." },
  { id: 53, level: 2, word: "청소하다", pronunciation: "cheongsohada", meaning: "цэвэрлэх", pos: "Үйл үг", exampleKo: "오늘 집을 깨끗이 청소했어요.", exampleMn: "Өнөөдөр гэрээ цэвэрхэн цэвэрлэсэн." },
  { id: 54, level: 2, word: "운동하다", pronunciation: "undonghada", meaning: "дасгал хийх", pos: "Үйл үг", exampleKo: "공원에서 매일 운동합니다.", exampleMn: "Цэцэрлэгт хүрээлэнд өдөр бүр дасгал хийдэг." },
  { id: 55, level: 2, word: "여행하다", pronunciation: "yeohaenghada", meaning: "аялах", pos: "Үйл үг", exampleKo: "여름 방학에 한국을 여행할 거예요.", exampleMn: "Зуны амралтаараа Солонгос улсаар аялах болно." },
  { id: 56, level: 2, word: "요리하다", pronunciation: "yorihada", meaning: "хоол хийх", pos: "Үйл үг", exampleKo: "어머니가 주방에서 요리하십니다.", exampleMn: "Ээж гал тогоонд хоол хийж байна." },
  { id: 57, level: 2, word: "운전하다", pronunciation: "unjeonhada", meaning: "жолоо барих", pos: "Үйл үг", exampleKo: "차를 조심해서 운전하세요.", exampleMn: "Машинаа болгоомжтой жолоодоорой." },
  { id: 58, level: 2, word: "시작하다", pronunciation: "sijakhada", meaning: "эхлэх", pos: "Үйл үг", exampleKo: "수업은 9시에 시작합니다.", exampleMn: "Хичээл 9 цагт эхэлнэ." },
  { id: 59, level: 2, word: "끝나다", pronunciation: "kkeutnada", meaning: "дуусах", pos: "Үйл үг", exampleKo: "회의가 마침내 끝났어요.", exampleMn: "Хурлууд эцэст нь дууслаа." },
  { id: 60, level: 2, word: "설명하다", pronunciation: "seolmyeonghada", meaning: "тайлбарлах", pos: "Үйл үг", exampleKo: "선생님이 문제를 설명해요.", exampleMn: "Багш асуудлыг тайлбарлаж байна." },
  { id: 61, level: 2, word: "약속", pronunciation: "yaksok", meaning: "амлалт/уулзалт", pos: "Нэр үг", exampleKo: "오늘 친구와 약속이 있어요.", exampleMn: "Өнөөдөр найзтайгаа уулзах уулзалттай." },
  { id: 62, level: 2, word: "시장", pronunciation: "sijang", meaning: "зах", pos: "Нэр үг", exampleKo: "시장에 사람이 많아요.", exampleMn: "Зах дээр хүн олон байна." },
  { id: 63, level: 2, word: "병원", pronunciation: "byeongwon", meaning: "эмнэлэг", pos: "Нэр үг", exampleKo: "감기 때문에 병원에 갔어요.", exampleMn: "Ханиад хүрснээс болоод эмнэлэг явсан." },
  { id: 64, level: 2, word: "약국", pronunciation: "yakguk", meaning: "эмийн сан", pos: "Нэр үг", exampleKo: "약국에서 감기약을 샀습니다.", exampleMn: "Эмийн сангаас ханиадны эм авсан." },
  { id: 65, level: 2, word: "은행", pronunciation: "eunhaeng", meaning: "банк", pos: "Нэр үг", exampleKo: "은행에서 돈을 찾았습니다.", exampleMn: "Банкнаас мөнгө авлаа." },
  { id: 66, level: 2, word: "회사", pronunciation: "hoesa", meaning: "компани", pos: "Нэр үг", exampleKo: "삼촌은 무역 회사에 다녀요.", exampleMn: "Ах маань худалдааны компанид ажилладаг." },
  { id: 67, level: 2, word: "지하철", pronunciation: "jihacheol", meaning: "метро", pos: "Нэр үг", exampleKo: "서울의 지하철은 편리합니다.", exampleMn: "Сөүлийн метро маш эвтэйхэн." },
  { id: 68, level: 2, word: "버스", pronunciation: "beoseu", meaning: "автобус", pos: "Нэр үг", exampleKo: "버스를 타고 학교에 가요.", exampleMn: "Автобусанд суугаад сургууль явдаг." },
  { id: 69, level: 2, word: "공항", pronunciation: "gonghang", meaning: "онгоцны буудал", pos: "Нэр үг", exampleKo: "공항에 손님이 가득합니다.", exampleMn: "Буудал дээр зорчигчдоор дүүрэн байна." },
  { id: 70, level: 2, word: "사진", pronunciation: "sajin", meaning: "зураг", pos: "Нэр үг", exampleKo: "예쁜 가족 사진을 찍었어요.", exampleMn: "Хөөрхөн гэр бүлийн зураг авсан." },
  { id: 71, level: 2, word: "취미", pronunciation: "chwimi", meaning: "хобби", pos: "Нэр үг", exampleKo: "제 취미는 사진 촬영입니다.", exampleMn: "Миний хобби бол зураг авах." },
  { id: 72, level: 2, word: "노래", pronunciation: "norae", meaning: "дуу", pos: "Нэр үг", exampleKo: "노래를 아주 잘 부르네요.", exampleMn: "Дуу үнэхээр сайн дуулдаг юм байна." },
  { id: 73, level: 2, word: "영화", pronunciation: "yeonghwa", meaning: "кино", pos: "Нэр үг", exampleKo: "어제 본 영화는 슬펐습니다.", exampleMn: "Өчигдөр үзсэн кино гунигтай байсан." },
  { id: 74, level: 2, word: "드라마", pronunciation: "deurama", meaning: "драм", pos: "Нэр үг", exampleKo: "한국 드라마가 몽골에서 인기 있습니다.", exampleMn: "Солонгос драм Монголд алдартай." },
  { id: 75, level: 2, word: "문제", pronunciation: "munje", meaning: "асуудал", pos: "Нэр үг", exampleKo: "이 문제는 너무 어렵습니다.", exampleMn: "Энэ асуудал үнэхээр хэцүү." },
  { id: 76, level: 2, word: "시험", pronunciation: "siheom", meaning: "шалгалт", pos: "Нэр үг", exampleKo: "다음 주에 큰 시험이 있어요.", exampleMn: "Дараагийн долоо хоногт том шалгалттай." },
  { id: 77, level: 2, word: "숙제", pronunciation: "sukje", meaning: "гэрийн даалгавар", pos: "Нэр үг", exampleKo: "숙제를 다 끝내고 자요.", exampleMn: "Даалгавраа бүрэн дуусгаад унтдаг." },
  { id: 78, level: 2, word: "계획", pronunciation: "gyehwek", meaning: "төлөвлөгөө", pos: "Нэр үг", exampleKo: "주말 계획을 세웠습니까?", exampleMn: "Амралтын өдрүүдийн төлөвлөгөөгөө гаргасан уу?" },
  { id: 79, level: 2, word: "건강", pronunciation: "geongang", meaning: "эрүүл мэнд", pos: "Нэр үг", exampleKo: "건강은 일생에서 가장 소중합니다.", exampleMn: "Эрүүл мэнд амьдралд хамгийн чухал." },
  { id: 80, level: 2, word: "감기", pronunciation: "gamgi", meaning: "ханиад", pos: "Нэр үг", exampleKo: "날씨가 추워서 감기에 걸렸어요.", exampleMn: "Хүйтэн байснаас болоод ханиад хүрчихлээ." },
  { id: 81, level: 2, word: "아프다", pronunciation: "apeuda", meaning: "өвдөх", pos: "Тэмдэг нэр", exampleKo: "머리가 몹시 아픕니다.", exampleMn: "Толгой маш их өвдөж байна." },
  { id: 82, level: 2, word: "바쁘다", pronunciation: "bappeuda", meaning: "завгүй", pos: "Тэмдэг нэр", exampleKo: "요즘 일이 많아서 바빠요.", exampleMn: "Сүүлийн үед ажил ихтэй завгүй байна." },
  { id: 83, level: 2, word: "피곤하다", pronunciation: "pigonhada", meaning: "ядарсан", pos: "Тэмдэг нэр", exampleKo: "일을 많이 해서 너무 피곤해요.", exampleMn: "Их ажилласнаас болоод үнэхээр ядарчээ." },
  { id: 84, level: 2, word: "친절하다", pronunciation: "chinjeolhada", meaning: "эелдэг", pos: "Тэмдэг нэр", exampleKo: "상점의 주인이 아주 친절합니다.", exampleMn: "Дэлгүүрийн эзэн үнэхээр эелдэг юм." },
  { id: 85, level: 2, word: "유명하다", pronunciation: "yumyeonghada", meaning: "алдартай", pos: "Тэмдэг нэр", exampleKo: "이곳은 아주 유명한 맛집입니다.", exampleMn: "Энэ бол үнэхээр алдартай хоолны газар." },
  { id: 86, level: 2, word: "필요하다", pronunciation: "piryohada", meaning: "хэрэгтэй", pos: "Тэмдэг нэр", exampleKo: "외국어 공부에는 사전이 필요해요.", exampleMn: "Гадаад хэл сурахад толь бичиг хэрэгтэй." },
  { id: 87, level: 2, word: "위험하다", pronunciation: "wiheomhada", meaning: "аюултай", pos: "Тэмдэг нэр", exampleKo: "밤늦게 산책하는 것은 위험해요.", exampleMn: "Шөнө орой алхах нь аюултай." },
  { id: 88, level: 2, word: "조용하다", pronunciation: "joyonghada", meaning: "чимээгүй", pos: "Тэмдэг нэр", exampleKo: "도서관 안은 조용해야 합니다.", exampleMn: "Номын сан дотор чимээгүй байх ёстой." },
  { id: 89, level: 2, word: "깨끗하다", pronunciation: "kkaekkeuthada", meaning: "цэвэрхэн", pos: "Тэмдэг нэр", exampleKo: "방이 아주 깨끗하군요.", exampleMn: "Өрөө үнэхээр цэвэрхэн байна шүү." },
  { id: 90, level: 2, word: "재미있다", pronunciation: "jaemiisda", meaning: "сонирхолтой", pos: "Тэмдэг нэр", exampleKo: "어제 읽은 소설책은 재미있었어요.", exampleMn: "Өчигдөр уншсан тууж сонирхолтой байсан." },
  { id: 91, level: 2, word: "어렵다", pronunciation: "eoryeopda", meaning: "хэцүү", pos: "Тэмдэг нэр", exampleKo: "이 한자 공부는 너무 어렵네요.", exampleMn: "Энэ ханз үсэг сурах нь маш хэцүү." },
  { id: 92, level: 2, word: "쉽다", pronunciation: "swipda", meaning: "амархан", pos: "Тэмдэг нэр", exampleKo: "한국어 발음은 비교적 쉬워요.", exampleMn: "Солонгос хэлний дуудлага харьцангуй амархан." },
  { id: 93, level: 2, word: "빠르다", pronunciation: "ppareuda", meaning: "хурдан", pos: "Тэмдэг нэр", exampleKo: "지하철이 제일 빠르고 편리합니다.", exampleMn: "Метро хамгийн хурдан бөгөөд амар байдаг." },
  { id: 94, level: 2, word: "느리다", pronunciation: "neurida", meaning: "удаан", pos: "Тэмдэг нэр", exampleKo: "인터넷 속도가 오늘 느립니다.", exampleMn: "Өнөөдөр интернетийн хурд удаан байна." },
  { id: 95, level: 2, word: "춥다", pronunciation: "chupda", meaning: "хүйтэн", pos: "Тэмдэг нэр", exampleKo: "몽골의 겨울은 매우 춥습니다.", exampleMn: "Монголын өвөл маш хүйтэн байдаг." },
  { id: 96, level: 2, word: "덥다", pronunciation: "deopda", meaning: "халуун", pos: "Тэмдэг нэр", exampleKo: "여름은 날씨가 더워서 수영장에 가요.", exampleMn: "Зун цаг агаар халуун болохоор усан бассейн явдаг." },
  { id: 97, level: 2, word: "멀다", pronunciation: "meolda", meaning: "хол", pos: "Тэмдэг нэр", exampleKo: "회사가 집에서 너무 멉니다.", exampleMn: "Компани гэрээс маш хол байна." },
  { id: 98, level: 2, word: "가깝다", pronunciation: "gakkapda", meaning: "ойр", pos: "Тэмдэг нэр", exampleKo: "시장이 역에서 가깝습니다.", exampleMn: "Зах нь буудлаас ойрхон." },
  { id: 99, level: 2, word: "비싸다", pronunciation: "bissaada", meaning: "үнэтэй", pos: "Тэмдэг нэр", exampleKo: "백화점 물건은 조금 비쌉니다.", exampleMn: "Их дэлгүүрийн бараа бага зэрэг үнэтэй." },
  { id: 100, level: 2, word: "싸다", pronunciation: "ssada", meaning: "хямд", pos: "Тэмдэг нэр", exampleKo: "이 옷은 가격이 저렴하고 쌉니다.", exampleMn: "Энэ хувцасны үнэ боломжийн бөгөөд хямд." },

  // ================= LEVEL 3 (101 - 150) =================
  { id: 101, level: 3, word: "경험", pronunciation: "gyeongheom", meaning: "туршлага", pos: "Нэр үг", exampleKo: "해외 봉사 경험을 쌓고 싶어요.", exampleMn: "Хилийн чанадад сайн дурын ажил хийж туршлага хуримтлуулахыг хүсэж байна." },
  { id: 102, level: 3, word: "실수", pronunciation: "silsu", meaning: "алдаа", pos: "Нэр үг", exampleKo: "누구나 실수를 할 수 있습니다.", exampleMn: "Хэн ч гэсэн алдаа гаргаж болно." },
  { id: 103, level: 3, word: "성공", pronunciation: "seonggong", meaning: "амжилт", pos: "Нэр үг", exampleKo: "노력은 성공의 필수 조건입니다.", exampleMn: "Хичээл зүтгэл бол амжилтын зайлшгүй нөхцөл." },
  { id: 104, level: 3, word: "실패", pronunciation: "silpae", meaning: "бүтэлгүйтэл", pos: "Нэр үг", exampleKo: "실패는 성공의 어머니입니다.", exampleMn: "Бүтэлгүйтэл бол амжилтын эх сурвалж (эх)." },
  { id: 105, level: 3, word: "노력", pronunciation: "noryeok", meaning: "хичээл", pos: "Нэр үг", exampleKo: "앞으로 많은 노력이 필요해요.", exampleMn: "Цаашид маш их хичээл зүтгэл шаардлагатай." },
  { id: 106, level: 3, word: "문화", pronunciation: "munhwa", meaning: "соёл", pos: "Нэр үг", exampleKo: "한국의 전통 문화를 체험했습니다.", exampleMn: "Солонгосын уламжлалт соёлтой танилцсан." },
  { id: 107, level: 3, word: "전통", pronunciation: "jeontong", meaning: "уламжлал", pos: "Нэр үг", exampleKo: "수백 년 된 유구한 전통입니다.", exampleMn: "Зуун зууны түүхтэй баялаг уламжлал." },
  { id: 108, level: 3, word: "사회", pronunciation: "sahoe", meaning: "нийгэм", pos: "Нэр үг", exampleKo: "다양한 사회 문제를 해결해야 합니다.", exampleMn: "Нийгмийн олон төрлийн асуудлуудыг шийдэх ёстой." },
  { id: 109, level: 3, word: "환경", pronunciation: "hwangyeong", meaning: "орчин", pos: "Нэр үг", exampleKo: "자연 환경을 잘 지킵시다.", exampleMn: "Байгалийн орчноо сайн хамгаалцгаая." },
  { id: 110, level: 3, word: "관계", pronunciation: "gwangye", meaning: "харилцаа", pos: "Нэр үг", exampleKo: "두 사람은 아주 친한 관계입니다.", exampleMn: "Энэ хоёр маш дотно харилцаатай." },
  { id: 111, level: 3, word: "스트레스", pronunciation: "seuteureseu", meaning: "стресс", pos: "Нэр үг", exampleKo: "운동은 스트레스 해소에 좋습니다.", exampleMn: "Дасгал хөдөлгөөн стресс тайлахад сайн." },
  { id: 112, level: 3, word: "자신감", pronunciation: "jasingam", meaning: "өөртөө итгэх итгэл", pos: "Нэр үг", exampleKo: "말할 때는 자신감이 아주 중요해요.", exampleMn: "Ярих үед өөртөө итгэх итгэл маш чухал." },
  { id: 113, level: 3, word: "성격", pronunciation: "seonggyeok", meaning: "зан чанар", pos: "Нэр үг", exampleKo: "그녀는 밝고 쾌활한 성격입니다.", exampleMn: "Тэр бүсгүй гэрэлтэй бөгөөд сэргэлэн зантай." },
  { id: 114, level: 3, word: "장점", pronunciation: "jangjeom", meaning: "давуу тал", pos: "Нэр үг", exampleKo: "그의 가장 큰 장점은 성실성입니다.", exampleMn: "Түүний хамгийн том давуу тал бол идэвхтэй/чин сэтгэлт байдал." },
  { id: 115, level: 3, word: "단점", pronunciation: "danjeom", meaning: "сул тал", pos: "Нэр үг", exampleKo: "자신의 단점을 보완해야 합니다.", exampleMn: "Өөрийн сул талыг нөхөн засах хэрэгтэй." },
  { id: 116, level: 3, word: "습관", pronunciation: "seupgwan", meaning: "зуршил", pos: "Нэр үг", exampleKo: "매일 아침 일찍 읽는 습관을 만들었어요.", exampleMn: "Өглөө бүр эрт унших зуршлыг бий болгосон." },
  { id: 117, level: 3, word: "기억", pronunciation: "gieok", meaning: "дурсамж", pos: "Нэр үг", exampleKo: "어릴 적 행복했던 기억이 납니다.", exampleMn: "Бага насны жаргалтай дурсамж сэргэж байна." },
  { id: 118, level: 3, word: "꿈", pronunciation: "kkum", meaning: "мөрөөдөл", pos: "Нэр үг", exampleKo: "어릴 때부터 제 꿈은 의사였습니다.", exampleMn: "Бага наснаас эхлэн миний мөрөөдөл эмч байсан." },
  { id: 119, level: 3, word: "목표", pronunciation: "mokpyo", meaning: "зорилго", pos: "Нэр үг", exampleKo: "올해 목표는 시험 합격입니다.", exampleMn: "Энэ оны зорилго бол шалгалтанд тэнцэх." },
  { id: 120, level: 3, word: "미래", pronunciation: "mirae", meaning: "ирээдүй", pos: "Нэр үг", exampleKo: "밝은 미래를 위해 노력합시다.", exampleMn: "Гэрэлт ирээдүйн төлөө хамтдаа хичээцгээе." },
  { id: 121, level: 3, word: "해결하다", pronunciation: "haegyeolhada", meaning: "шийдэх", pos: "Үйл үг", exampleKo: "문제를 신속히 해결했습니다.", exampleMn: "Асуудлыг шуурхай шийдвэрлэсэн." },
  { id: 122, level: 3, word: "비교하다", pronunciation: "bigyohada", meaning: "харьцуулах", pos: "Үйл үг", exampleKo: "다른 사람과 나를 비교하지 마세요.", exampleMn: "Бусад хүнтэй өөрийгөө бүү харьцуул." },
  { id: 123, level: 3, word: "선택하다", pronunciation: "seontaekhada", meaning: "сонгох", pos: "Үйл үг", exampleKo: "어떤 전공을 선택할 것인가?", exampleMn: "Ямар мэргэжлийг сонгох гэж байна вэ?" },
  { id: 124, level: 3, word: "결정하다", pronunciation: "gyeoljeonghada", meaning: "шийдвэрлэх", pos: "Үйл үг", exampleKo: "최종 약속 시간을 오늘 결정해요.", exampleMn: "Эцсийн уулзалтын цагийг өнөөдөр шийднэ." },
  { id: 125, level: 3, word: "포기하다", pronunciation: "pogihada", meaning: "бууж өгөх", pos: "Үйл үг", exampleKo: "어떤 순간에도 절대 포기하지 마라.", exampleMn: "Ямар ч мөчид хэзээ ч бүү бууж өг." },
  { id: 126, level: 3, word: "도전하다", pronunciation: "dojeonhada", meaning: "сорих", pos: "Үйл үг", exampleKo: "새로운 과제에 과감하게 도전해요.", exampleMn: "Шинэ сорилтыг зоригтойгоор туршиж үзэцгээе." },
  { id: 127, level: 3, word: "걱정하다", pronunciation: "geokjeonghada", meaning: "санаа зовох", pos: "Үйл үг", exampleKo: "너무 큰 걱정은 하지 마세요.", exampleMn: "Хэтэрхий их санаа бүү зов." },
  { id: 128, level: 3, word: "추천하다", pronunciation: "chucheonhada", meaning: "санал болгох", pos: "Үйл үг", exampleKo: "재미있는 책을 추천해 주시겠습니까?", exampleMn: "Сонирхолтой ном санал болгож өгөхгүй юу?" },
  { id: 129, level: 3, word: "동의하다", pronunciation: "donguihada", meaning: "зөвшөөрөх", pos: "Үйл үг", exampleKo: "그의 제안에 전적으로 동의합니다.", exampleMn: "Түүний саналд бүрэн зөвшөөрч байна." },
  { id: 130, level: 3, word: "반대하다", pronunciation: "bandaehada", meaning: "эсэргүүцэх", pos: "Үйл үг", exampleKo: "다수의 사람들이 법안에 반대했다.", exampleMn: "Маш олон хүн уг хуулийг эсэргүүцсэн." },
  { id: 131, level: 3, word: "증가하다", pronunciation: "jeunggahada", meaning: "нэмэгдэх", pos: "Үйл үг", exampleKo: "외국인 관광객 수가 급격히 증가했다.", exampleMn: "Гадаадын жуулчдын тоо маш хурдан нэмэгдсэн." },
  { id: 132, level: 3, word: "감소하다", pronunciation: "gamsohada", meaning: "буурах", pos: "Үйл үг", exampleKo: "출산율이 갈수록 감소하고 있습니다.", exampleMn: "Төрөлтийн хувь жилээс жилд буурч байна." },
  { id: 133, level: 3, word: "발전하다", pronunciation: "baljeonhada", meaning: "хөгжих", pos: "Үйл үг", exampleKo: "과학 기술이 눈부시게 발전했어요.", exampleMn: "Шинжлэх ухаан технологи гайхалтай хөгжжээ." },
  { id: 134, level: 3, word: "변하다", pronunciation: "byeonhada", meaning: "өөрчлөгдөх", pos: "Үйл үг", exampleKo: "강산이 10년이면 변한다고 합니다.", exampleMn: "Орчин 10 жилд өөрчлөгддөг гэдэг." },
  { id: 135, level: 3, word: "유지하다", pronunciation: "yujihada", meaning: "хадгалах", pos: "Үйл үг", exampleKo: "건강한 체중을 꾸준히 유지해요.", exampleMn: "Эрүүл жингээ тогтмол хадгалдаг." },
  { id: 136, level: 3, word: "발생하다", pronunciation: "balsaenghada", meaning: "үүүсэх", pos: "Үйл үг", exampleKo: "길에서 접촉 사고가 발생했습니다.", exampleMn: "Зам дээр мөргөлдөх осол үүссэн." },
  { id: 137, level: 3, word: "포함하다", pronunciation: "pohamhada", meaning: "багтаах", pos: "Үйл үг", exampleKo: "가격에 세금이 포함되어 있습니다.", exampleMn: "Үнэд татвар багтсан байгаа." },
  { id: 138, level: 3, word: "강조하다", pronunciation: "gangjohada", meaning: "онцлох", pos: "Үйл үг", exampleKo: "중요성을 특별히 강조하고 있다.", exampleMn: "Чухал байдлыг нь онцгойлон онцолж байна." },
  { id: 139, level: 3, word: "존중하다", pronunciation: "jonjunghada", meaning: "хүндлэх", pos: "Үйл үг", exampleKo: "타인의 사생활을 마땅히 존중합시다.", exampleMn: "Бусдын хувийн амьдралыг хүндэтгэцгээе." },
  { id: 140, level: 3, word: "이해하다", pronunciation: "ihaehada", meaning: "ойлгох", pos: "Үйл үг", exampleKo: "선생님의 설명을 완전히 이해했습니다.", exampleMn: "Багшийн тайлбарыг бүрэн ойлголоо." },
  { id: 141, level: 3, word: "발표하다", pronunciation: "balpyohada", meaning: "илтгэх", pos: "Үйл үг", exampleKo: "어제 새로운 연구 결과를 발표했다.", exampleMn: "Өчигдөр шинэ судалгааны үр дүнгээ танилцуулсан." },
  { id: 142, level: 3, word: "토론하다", pronunciation: "toronhada", meaning: "хэлэлцэх", pos: "Үйл үг", exampleKo: "환경 문제에 대해 열띤 토론을 나눴다.", exampleMn: "Байгаль орчны асуудлаар халуун хэлэлцүүлэг өрнүүллээ." },
  { id: 143, level: 3, word: "조사하다", pronunciation: "josahada", meaning: "судлах", pos: "Үйл үг", exampleKo: "소비자 선호도를 자세히 조사해요.", exampleMn: "Хэрэглэгчийн таашаалыг нарийвчлан судалж байна." },
  { id: 144, level: 3, word: "관리하다", pronunciation: "gwanrihada", meaning: "удирдах", pos: "Үйл үг", exampleKo: "시간 관리를 철저히 해야 합니다.", exampleMn: "Цаг ашиглалтаа сайн удирдах ёстой." },
  { id: 145, level: 3, word: "이용하다", pronunciation: "iyonghada", meaning: "ашиглах", pos: "Үйл үг", exampleKo: "대중교통을 적극 이용합시다.", exampleMn: "Нийтийн тээврийг идэвхтэй ашиглацгаая." },
  { id: 146, level: 3, word: "보호하다", pronunciation: "bohohada", meaning: "хамгаалах", pos: "Үйл үг", exampleKo: "멸종 위기 동물을 보호해야 해요.", exampleMn: "Мөхөх аюулд орсон амьтдыг хамгаалах ёстой." },
  { id: 147, level: 3, word: "감소시키다", pronunciation: "gamsosikida", meaning: "бууруулах", pos: "Үйл үг", exampleKo: "비용을 최소한으로 감소시켰습니다.", exampleMn: "Зардлыг хамгийн бага түвшинд хүртэл бууруулсан." },
  { id: 148, level: 3, word: "소비하다", pronunciation: "sobihada", meaning: "хэрэглэх", pos: "Үйл үг", exampleKo: "에너지를 효율적으로 소비해야 합니다.", exampleMn: "Эрчим хүчийг үр ашигтайгаар хэрэглэх хэрэгтэй." },
  { id: 149, level: 3, word: "생산하다", pronunciation: "saengsanhada", meaning: "үйлдвэрлэх", pos: "Үйл үг", exampleKo: "스마트폰을 공장에서 대량 생산한다.",
  exampleMn: "Ухаалаг утсыг үйлдвэрт олноор үйлдвэрлэдэг." },
  { id: 150, level: 3, word: "개발하다", pronunciation: "gaebalhada", meaning: "хөгжүүлэх", pos: "Үйл үг", exampleKo: "신기술을 끊임없이 개발하고 있습니다.", exampleMn: "Шинэ технологийг тасралтгүй хөгжүүлж байна." },

  // ================= LEVEL 4 (151 - 200) =================
  { id: 151, level: 4, word: "교육", pronunciation: "gyoyuk", meaning: "боловсрол", pos: "Нэр үг", exampleKo: "초등 교육은 필수입니다.", exampleMn: "Бага боловсрол зайлшгүй шаардлагатай." },
  { id: 152, level: 4, word: "경제", pronunciation: "gyeongje", meaning: "эдийн засаг", pos: "Нэр үг", exampleKo: "세계 경제가 빠르게 침체하고 있다.", exampleMn: "Дэлхийн эдийн засаг маш хурдан уналтад орж байна." },
  { id: 153, level: 4, word: "기술", pronunciation: "gisul", meaning: "технологи", pos: "Нэр үг", exampleKo: "인공지능 기술이 발전했습니다.", exampleMn: "Хиймэл оюун ухааны технологи хөгжжээ." },
  { id: 154, level: 4, word: "산업", pronunciation: "saneop", meaning: "үйлдвэрлэл", pos: "Нэр үг", exampleKo: "4차 산업 혁명이 다가왔습니다.", exampleMn: "Аж үйлдвэрийн 4-р хувьсгал хаяанд ирлээ." },
  { id: 155, level: 4, word: "정보", pronunciation: "jeongbo", meaning: "мэдээлэл", pos: "Нэр үг", exampleKo: "유용한 정보를 공유해 드립니다.", exampleMn: "Хэрэгтэй мэдээллийг хуваалцаж байна." },
  { id: 156, level: 4, word: "인터넷", pronunciation: "inteonet", meaning: "интернет", pos: "Нэр үг", exampleKo: "인터넷이 연결되어 있지 않아요.", exampleMn: "Интернет холбогдоогүй байна." },
  { id: 157, level: 4, word: "소통", pronunciation: "sotong", meaning: "харилцаа", pos: "Нэр үг", exampleKo: "가족 간의 대화와 소통이 필요합니다.", exampleMn: "Гэр бүл хоорондын харилцаа шаардлагатай." },
  { id: 158, level: 4, word: "경쟁", pronunciation: "gyeongjaeng", meaning: "өрсөлдөөн", pos: "Нэр үг", exampleKo: "입시 경쟁이 날로 치열해지고 있다.",
  exampleMn: "Шалгалтын өрсөлдөөн өдөр ирэх тусам ширүүсэж байна." },
  { id: 159, level: 4, word: "책임", pronunciation: "chaegim", meaning: "хариуцлага", pos: "Нэр үг", exampleKo: "스스로 행동에 책임을 져야 합니다.", exampleMn: "Өөрийн үйлдэлд өөрөө хариуцлага хүлээх ёстой." },
  { id: 160, level: 4, word: "권리", pronunciation: "gwonri", meaning: "эрх", pos: "Нэр үг", exampleKo: "우리는 노동의 권리를 요구합니다.", exampleMn: "Бид хөдөлмөрлөх эрхээ шаардаж байна." },
  { id: 161, level: 4, word: "의무", pronunciation: "uimu", meaning: "үүрэг", pos: "Нэр үг", exampleKo: "국방의 의무를 충실히 다하고 있다.", exampleMn: "Батлан хамгаалах үүргээ үнэнчээр биелүүлж байна." },
  { id: 162, level: 4, word: "정책", pronunciation: "jeongchaek", meaning: "бодлого", pos: "Нэр үг", exampleKo: "정부의 부동산 정책이 발표되었다.", exampleMn: "Засгийн газрын үл хөдлөх хөрөнгийн бодлого танилцуулагдлаа." },
  { id: 163, level: 4, word: "제도", pronunciation: "jedo", meaning: "тогтолцоо", pos: "Нэр үг", exampleKo: "새로운 사회 복지 제도가 통과되었다.", exampleMn: "Нийгмийн халамжийн шинэ тогтолцоо батлагдлао." },
  { id: 164, level: 4, word: "현상", pronunciation: "hyeonsang", meaning: "үзэгдэл", pos: "Нэр үг", exampleKo: "지구 온난화 현상이 심각해지고 있다.", exampleMn: "Дэлхийн дулаарлын үзэгдэл ноцтой болж байна." },
  { id: 165, level: 4, word: "원인", pronunciation: "wonin", meaning: "шалтгаан", pos: "Нэр үг", exampleKo: "정확한 병의 원인을 밝혀야 합니다.", exampleMn: "Өвчний тодорхой шалтгааныг тодруулах хэрэгтэй." },
  { id: 166, level: 4, word: "결과", pronunciation: "gyeolgua", meaning: "үр дүн", pos: "Нэр үг", exampleKo: "노력의 결과는 항상 정직합니다.", exampleMn: "Хичээл зүтгэлийн үр дүн үргэлж шударга байдаг." },
  { id: 167, level: 4, word: "영향", pronunciation: "yeonghyang", meaning: "нөлөө", pos: "Нэр үг", exampleKo: "부모는 자식에게 큰 영향을 줍니다.", exampleMn: "Эцэг эх хүүхдүүддээ маш их нөлөө үзүүлдэг." },
  { id: 168, level: 4, word: "가치", pronunciation: "gachi", meaning: "үнэ цэнэ", pos: "Нэр үг", exampleKo: "시간은 큰 내면적 가치가 있다.", exampleMn: "Цаг хугацаа нь дотоод асар их үнэ цэнэтэй." },
  { id: 169, level: 4, word: "태도", pronunciation: "taedo", meaning: "хандлага", pos: "Нэр үг", exampleKo: "배우려는 적극적인 태도를 유지해요.", exampleMn: "Суралцах гэсэн идэвхтэй хандлагаа хадгалдаг." },
  { id: 170, level: 4, word: "의견", pronunciation: "uigyeon", meaning: "санал бодол", pos: "Нэр үг", exampleKo: "서로 다른 의견을 충분히 조율했습니다.", exampleMn: "Бие биенийхээ ялгаатай санал бодлыг зохицуулсан." },
  { id: 171, level: 4, word: "주장하다", pronunciation: "jujanghada", meaning: "주장лах (батлах/шаардах)", pos: "Үйл үг", exampleKo: "자신의 정당성을 거듭 주장했다.", exampleMn: "Өөрийн зөв байдлаа дахин дахин баталсан." },
  { id: 172, level: 4, word: "표현하다", pronunciation: "pyohyeonhada", meaning: "илэрхийлэх", pos: "Үйл үг", exampleKo: "사랑을 글로 조심스레 표현했습니다.", exampleMn: "Хайраа бичгээр зөөлнөөр илэрхийлсэн." },
  { id: 173, level: 4, word: "적용하다", pronunciation: "jeogyonghada", meaning: "хэрэглэх (нийцүүлэх)", pos: "Үйл үг", exampleKo: "새 공식을 실제 문제에 적용했다.", exampleMn: "Шинэ томьёог бодит асуудалд ашигласан/нийцүүлсэн." },
  { id: 174, level: 4, word: "분석하다", pronunciation: "bunseokhada", meaning: "дүн шинжилгээ хийх", pos: "Үйл үг", exampleKo: "수집한 데이터를 세밀히 분석했다.", exampleMn: "Цуглуулсан өгөгдөлдөө нарийвчлан шинжилгээ хийсэн." },
  { id: 175, level: 4, word: "평가하다", pronunciation: "pyonggahada", meaning: "үнэлэх", pos: "Үйл үг", exampleKo: "교사의 실적을 다방면으로 평가했다.", exampleMn: "Багшийн ажлын үр дүнг олон талаас нь үнэллээ." },
  { id: 176, level: 4, word: "개선하다", pronunciation: "gaeseonhada", meaning: "сайжруулах", pos: "Үйл үг", exampleKo: "열악한 근무 환경을 조속히 개선했다.", exampleMn: "Ажлын таагүй орчныг хурдан сайжруулсан." },
  { id: 177, level: 4, word: "예방하다", pronunciation: "yebanghada", meaning: "урьдчилан сэргийлэх", pos: "Үйл үг", exampleKo: "질병을 예방하기 위한 백신 주사를 맞았다.", exampleMn: "Өвчнөөс урьдчилан сэргийлэх вакцин тариулсан." },
  { id: 178, level: 4, word: "실현하다", pronunciation: "silhyeonhada", meaning: "хэрэгжүүлэх (биелүүлэх)", pos: "Үйл үг", exampleKo: "오랜 꿈을 마침내 현실로 실현했다.", exampleMn: "Удаан хугацааны мөрөөдлөө эцэст нь бодит болгон биелүүлсэн." },
  { id: 179, level: 4, word: "참여하다", pronunciation: "chamyeohada", meaning: "оролцох", pos: "Үйл үг", exampleKo: "지역 봉사 활동에 적극 참여했다.", exampleMn: "Орон нутгийн сайн дурын ажилд идэвхтэй оролцсон." },
  { id: 180, level: 4, word: "확대되다", pronunciation: "hwagdaedweda", meaning: "өргөжих", pos: "Үйл үг", exampleKo: "사업 영역이 세계 각국으로 확대되었다.", exampleMn: "Бизнесийн салбар дэлхийн олон оронд өргөжлөө." },
  { id: 181, level: 4, word: "축소되다", pronunciation: "chuksodweda", meaning: "багасах", pos: "Үйл үг", exampleKo: "조직 규모가 대폭 축소되었습니다.", exampleMn: "Байгууллагын бүтэц хэмжээ ихээхэн багассан." },
  { id: 182, level: 4, word: "강조되다", pronunciation: "gangjodweda", meaning: "онцлогдох", pos: "Үйл үг", exampleKo: "기초의 중요성이 다시금 강조되고 있다.", exampleMn: "Суурийн чухал ач холбогдол дахин онцлогдож байна." },
  { id: 183, level: 4, word: "연결되다", pronunciation: "yeongyeoldweda", meaning: "холбогдох", pos: "Үйл үг", exampleKo: "도로가 항구와 직접 연결되어 있습니다.", exampleMn: "Зам нь боомттой шууд холбогдсон байдаг." },
  { id: 184, level: 4, word: "구성되다", pronunciation: "guseongdweda", meaning: "бүрдэх", pos: "Үйл үг", exampleKo: "우리 위원회는 총 7명으로 구성되었다.", exampleMn: "Манай хороо нийт 7 хүнээс бүрдсэн." },
  { id: 185, level: 4, word: "달성하다", pronunciation: "dalseonghada", meaning: "биелүүлэх (хүрэх)", pos: "Үйл үг", exampleKo: "분기 매출 목표를 조기에 달성했습니다.", exampleMn: "Улирлын борлуулалтын зорилтоо хугацаанаас нь өмнө биелүүлсэн." },
  { id: 186, level: 4, word: "유지되다", pronunciation: "yujidweda", meaning: "хадгалагдах", pos: "Үйл үг", exampleKo: "평화로운 분위기가 오래 유지되었다.", exampleMn: "Тайван сайхан уур амьсгал удаан хадгалагдлаа." },
  { id: 187, level: 4, word: "제한하다", pronunciation: "jehanhada", meaning: "хязгаарлах", pos: "Үйл үг", exampleKo: "과도한 지출을 법적으로 제한하고 있다.", exampleMn: "Хэт их үрэлгэн байдлыг хуулиар хязгаарласан байдаг." },
  { id: 188, level: 4, word: "소비자", pronunciation: "sobijja", meaning: "хэрэглэгч", pos: "Нэр үг", exampleKo: "소비자들의 만족도를 조사했다.", exampleMn: "Хэрэглэгчдийн сэтгэл ханамжийг судалсан." },
  { id: 189, level: 4, word: "전문가", pronunciation: "jeonmunga", meaning: "мэргэжилтэн", pos: "Нэр үг", exampleKo: "전문가의 의견을 구하러 갔습니다.", exampleMn: "Мэргэжилтний санал бодлыг авахаар очлоо." },
  { id: 190, level: 4, word: "청소년", pronunciation: "cheongsonyeon", meaning: "өсвөр насны хүүхэд", pos: "Нэр үг", exampleKo: "청소년 교육 문제를 진지하게 토론했다.", exampleMn: "Өсвөр насны хүүхдүүдийн боловсролыг нухацтай хэлэлцсэн." },
  { id: 191, level: 4, word: "노인", pronunciation: "noin", meaning: "ахмад настан", pos: "Нэр үг", exampleKo: "독거 노인을 돕는 연말 행사를 열었다.", exampleMn: "Ганц бие ахмадуудад туслах шинэ оны баяр зохион байгууллаа." },
  { id: 192, level: 4, word: "정부", pronunciation: "jeongbu", meaning: "засгийн газар", pos: "Нэр үг", exampleKo: "정부 예산안이 국회에 승인되었다.", exampleMn: "Засгийн газрын төсөв парламентаар батлагдсан." },
  { id: 193, level: 4, word: "기업", pronunciation: "gieop", meaning: "компани/аж ахуйн нэгж", pos: "Нэр үг", exampleKo: "외국계 유망 기업에 취직하고 싶다.", exampleMn: "Гадаадын ирээдүйтэй компанид ажилд орохыг хүсэж байна." },
  { id: 194, level: 4, word: "지역", pronunciation: "jiyeok", meaning: "бүс нутаг", pos: "Нэр үг", exampleKo: "지역 주민들을 위한 복지 센터입니다.", exampleMn: "Орон нутгийн оршин суугчдад зориулсан халамжийн төв." },
  { id: 195, level: 4, word: "국제", pronunciation: "gukje", meaning: "олон улсын", pos: "Нэр үг", exampleKo: "국제 협력 협정이 체결되었습니다.", exampleMn: "Олон улсын хамтын ажиллагааны гэрээ батлагдсан." },
  { id: 196, level: 4, word: "현대", pronunciation: "hyeondae", meaning: "орчин үе", pos: "Нэр үг", exampleKo: "현대 사회는 매우 바쁘고 빠르다.", exampleMn: "Орчин үеийн нийгэм маш завгүй бөгөөд хурдан." },
  { id: 197, level: 4, word: "전자제품", pronunciation: "jeonjajepum", meaning: "цахилгаан бараа", pos: "Нэр үг", exampleKo: "최신 전자제품을 매장에서 구경했다.", exampleMn: "Шинэ цахилгаан бараануудыг дэлгүүрт сонирхсон." },
  { id: 198, level: 4, word: "인공지능", pronunciation: "ingongjineung", meaning: "хиймэл оюун ухаан", pos: "Нэр үг", exampleKo: "인공지능은 다양한 직업을 바꾸고 있다.", exampleMn: "Хиймэл оюун ухаан олон ажлыг өөрчилж байна." },
  { id: 199, level: 4, word: "환경오염", pronunciation: "hwangyeongoyeom", meaning: "байгаль орчны бохирдол", pos: "Нэр үг", exampleKo: "환경오염 방지를 대책으로 마련했다.", exampleMn: "Байгаль орчны бохирдлоос урьдчилан сэргийлэх арга хэмжээг бэлдсэн." },
  { id: 200, level: 4, word: "기후변화", pronunciation: "gihubyeonhwa", meaning: "уур амьсгалын өөрчлөлт", pos: "Нэр үг", exampleKo: "기후변화는 인류가 당면한 큰 난제다.", exampleMn: "Уур амьсгалын өөрчлөлт бол хүн төрөлхтний өмнө тулгарсан том сорилт." },

  // ================= LEVEL 5 (201 - 250) =================
  { id: 201, level: 5, word: "갈등", pronunciation: "galdeung", meaning: "зөрчил", pos: "Нэр үг", exampleKo: "부서 간의 이견으로 생긴 갈등을 풀었다.", exampleMn: "Хэлтэс хоорондын санал зөрөлдөөнөөс үүссэн зөрчлийг шийдсэн." },
  { id: 202, level: 5, word: "차별", pronunciation: "chabyeol", meaning: "ялгаварлал", pos: "Нэр үг", exampleKo: "성별에 의한 부당한 차별을 금지한다.", exampleMn: "Хүйсээр ялгаварлан гадуурхахыг хориглоно." },
  { id: 203, level: 5, word: "편견", pronunciation: "pyeongyeon", meaning: "өрөөсгөл ойлголт", pos: "Нэр үг", exampleKo: "타인에 대한 깊은 편견을 깨뜨려라.", exampleMn: "Бусдын талаарх гүнзгий өрөөсгөл ойлголтоо устга." },
  { id: 204, level: 5, word: "윤리", pronunciation: "yulli", meaning: "ёс зүй", pos: "Нэр үг", exampleKo: "학자들은 연구 윤리를 준수해야 한다.", exampleMn: "Эрдэмтэд судалгааны ёс зүйг баримтлах ёстой." },
  { id: 205, level: 5, word: "복지", pronunciation: "bokji", meaning: "халамж", pos: "Нэр үг", exampleKo: "사회 취약 계층의 복지 혜택을 늘렸다.", exampleMn: "Нийгмийн эмзэг бүлгийн халамжийн тэтгэмжийг нэмэгдүүлсэн." },
  { id: 206, level: 5, word: "민주주의", pronunciation: "minjujuui", meaning: "ардчилал", pos: "Нэр үг", exampleKo: "대한민국은 민주주의 국가입니다.", exampleMn: "БНСУ бол ардчилсан улс юм." },
  { id: 207, level: 5, word: "자유", pronunciation: "jayu", meaning: "эрх чөлөө", pos: "Нэр үг", exampleKo: "헌법은 사상의 자유를 굳건히 보장한다.", exampleMn: "Үндсэн хуулиар үзэл бодлын эрх чөлөөг баттай хангадаг." },
  { id: 208, level: 5, word: "평등", pronunciation: "pyeongdeung", meaning: "тэгш байдал", pos: "Нэр үг", exampleKo: "법 앞에서 만인의 평등을 주창했다.", exampleMn: "Хуулийн өмнө бүх хүмүүс тэгш байхыг уриалсан." },
  { id: 209, level: 5, word: "범죄", pronunciation: "beomjoe", meaning: "гэмт хэрэг", pos: "Нэр үг", exampleKo: "청소년 범죄 증가율이 다소 우려스럽다.", exampleMn: "Өсвөр насныхны гэмт хэргийн нэмэгдэл бага зэрэг сэтгэл түгшээж байна." },
  { id: 210, level: 5, word: "법률", pronunciation: "beomnyul", meaning: "хууль", pos: "Нэр үг", exampleKo: "새로운 법률 조항이 정식으로 효력을 냈다.", exampleMn: "Шинэ хуулийн заалт албан ёсоор хүчин төгөлдөр боллоо." },
  { id: 211, level: 5, word: "심리", pronunciation: "simri", meaning: "сэтгэл зүй", pos: "Нэр үг", exampleKo: "아동 심리 분석 상담을 의뢰했습니다.", exampleMn: "Хүүхдийн сэтгэл зүйн шинжилгээний зөвлөгөө авах хүсэлт тавьсан." },
  { id: 212, level: 5, word: "철학", pronunciation: "cheolhak", meaning: "философи", pos: "Нэр үг", exampleKo: "그의 삶의 철학은 매우 단순합니다.", exampleMn: "Түүний амьдралын философи маш энгийн." },
  { id: 213, level: 5, word: "종교", pronunciation: "jonggyo", meaning: "шашин", pos: "Нэр үг", exampleKo: "개인의 종교적 자유를 전적으로 존중한다.", exampleMn: "Хувь хүний шашин шүтэх эрх чөлөөг бүрэн хүндэтгэнэ." },
  { id: 214, level: 5, word: "창의성", pronunciation: "changwiseong", meaning: "бүтээлч байдал", pos: "Нэр үг", exampleKo: "창의성 발달을 위한 특별 교재를 마련했다.", exampleMn: "Бүтээлч байдлыг хөгжүүлэх тусгай сурах бичиг бэлдсэн." },
  { id: 215, level: 5, word: "능력", pronunciation: "neungnyeok", meaning: "чадвар", pos: "Нэр үг", exampleKo: "업무 수행 능력을 훌륭히 증명해 보였다.", exampleMn: "Ажил гүйцэтгэх чадвараа гайхалтайгаар батлан харуулсан." },
  { id: 216, level: 5, word: "인상적이다", pronunciation: "insangjeogida", meaning: "сэтгэгдэл төрүүлэхүйц", pos: "Тэмдэг нэр", exampleKo: "박물관에서 본 미술품이 꽤 인상적이었다.", exampleMn: "Музейд үзсэн урлагийн бүтээл нэлээд сэтгэгдэл төрүүлэхүйц байлаа." },
  { id: 217, level: 5, word: "복잡하다", pronunciation: "bokjaphada", meaning: "төвөгтэй", pos: "Тэмдэг нэр", exampleKo: "인간관계는 때로 대단히 복잡하네요.", exampleMn: "Хүмүүсийн харилцаа заримдаа маш түвэгтэй байдаг." },
  { id: 218, level: 5, word: "적절하다", pronunciation: "jeokjeolhada", meaning: "тохиромжтой", pos: "Тэмдэг нэр", exampleKo: "상황에 맞는 적절한 처방을 내렸다.", exampleMn: "Нөхцөл байдалд тохирсон эмчилгээ хийсэн." },
  { id: 219, level: 5, word: "불리하다", pronunciation: "bullihada", meaning: "ашиггүй", pos: "Тэмдэг нэр", exampleKo: "우리의 소송 조건이 다소 불리합니다.", exampleMn: "Манай шүүхийн нөхцөл байдал бага зэрэг ашиггүй/таагүй байна." },
  { id: 220, level: 5, word: "유리하다", pronunciation: "yurihada", meaning: "ашигтай", pos: "Тэмдэг нэр", exampleKo: "지리학적으로 아시아 무역에 유리하다.", exampleMn: "Газарзүйн байршлын хувьд Азийн худалдаанд ашигтай." },
  { id: 221, level: 5, word: "기여하다", pronunciation: "giyeohada", meaning: "хувь нэмэр оруулах", pos: "Үйл үг", exampleKo: "국가 발전에 혁혁하게 기여했습니다.", exampleMn: "Улс орны хөгжилд ихээхэн хувь нэмэр оруулсан." },
  { id: 222, level: 5, word: "대응하다", pronunciation: "daeunghada", meaning: "대응 хийх (хариу арга хэмжээ авах)", pos: "Үйл үг", exampleKo: "재해 사태에 신속히 대응했다.", exampleMn: "Гамшгийн байдалд шуурхай хариу арга хэмжээ авсан." },
  { id: 223, level: 5, word: "극복하다", pronunciation: "geukbokhada", meaning: "даван туулах", pos: "Үйл үг", exampleKo: "수많은 재정적 시련을 다 극복했어요.", exampleMn: "Санхүүгийн асар олон сорилтыг бүгдийг нь даван туулсан." },
  { id: 224, level: 5, word: "촉진하다", pronunciation: "chokjinhada", meaning: "дэмжих/хурдасгах", pos: "Үйл үг", exampleKo: "경제 활성화를 적극적으로 촉진하고 있다.", exampleMn: "Эдийн засгийг эрчимжүүлэхийг идэвхтэй дэмжиж байна." },
  { id: 225, level: 5, word: "중단하다", pronunciation: "jungdanhada", meaning: "зогсоох", pos: "Үйл үг", exampleKo: "개발 계획을 일시 중단하기로 합의했다.", exampleMn: "Хөгжүүлэлтийн төлөвлөгөөг түр зогсоохоор тохиролцсон." },
  { id: 226, level: 5, word: "제거하다", pronunciation: "jegeohada", meaning: "арилгах", pos: "Үйл үг", exampleKo: "몸에 해로운 요소를 말끔히 제거했다.", exampleMn: "Биед хортой элементийг бүрэн арилгасан." },
  { id: 227, level: 5, word: "강조점", pronunciation: "gangjojeom", meaning: "онцлох зүйл", pos: "Нэр үг", exampleKo: "그 연구의 강조점은 실행 방안에 있다.", exampleMn: "Уг судалгааны онцлох зүйл нь хэрэгжүүлэх арга зам юм." },
  { id: 228, level: 5, word: "파악하다", pronunciation: "paakhada", meaning: "ойлгож мэдэх", pos: "Үйл үг", exampleKo: "진실을 밝히기 위해 사건 실태를 파악했다.", exampleMn: "Үнэнийг тогтоохын тулд хэргийн бодит байдлыг ойлгож мэдсэн." },
  { id: 229, level: 5, word: "인식하다", pronunciation: "insikhada", meaning: "ухамсарлах", pos: "Үйл үг", exampleKo: "심각성을 뒤늦게 깊이 인식하게 되었다.", exampleMn: "Ноцтой байдлыг сүүлд нь гүнээ ухамсарлах болсон." },
  { id: 230, level: 5, word: "간주하다", pronunciation: "ganjuhada", meaning: "гэж үзэх", pos: "Үйл үг", exampleKo: "이 계약을 공식적으로 유효하다고 간주한다.", exampleMn: "Энэхүү гэрээг албан ёсоор хүчинтэй гэж үзнэ." },
  { id: 231, level: 5, word: "판단하다", pronunciation: "pandanhada", meaning: "дүгнэх", pos: "Үйл үг", exampleKo: "겉모습으로 타인의 됨됨이를 판단하지 마라.", exampleMn: "Гадаад төрхөөр нь хүний зан чанарыг бүү дүгнэ." },
  { id: 232, level: 5, word: "비판하다", pronunciation: "bipanhada", meaning: "шүүмжлэх", pos: "Үйл үг", exampleKo: "타당한 이유 없이 남의 성과를 비판했다.", exampleMn: "Үндэслэлгүйгээр бусдын амжилтыг шүүмжилсэн." },
  { id: 233, level: 5, word: "설득하다", pronunciation: "seoldeukhada", meaning: "ятгах", pos: "Үйл үг", exampleKo: "반대 입장의 야당 국회의원을 마침내 설득했다.", exampleMn: "Эсрэг байр суурьтай сөрөг хүчний гишүүнийг эцэст нь ятгаж чадсан." },
  { id: 234, level: 5, word: "요구하다", pronunciation: "yoguhada", meaning: "шаардах", pos: "Үйл үг", exampleKo: "노동자들은 더 높은 도덕성을 요구하고 있다.", exampleMn: "Ажилчид илүү өндөр ёс суртахууныг шаардаж байна." },
  { id: 235, level: 5, word: "허용하다", pronunciation: "heoyonghada", meaning: "зөвшөөрөх", pos: "Үйл үг", exampleKo: "미성년자의 출입을 엄격히 허용하지 않는다.", exampleMn: "Насанд хүрээгүй хүүхэд нэвтрэхийг зөвшөөрөхгүй." },
  { id: 236, level: 5, word: "거부하다", pronunciation: "geobuhada", meaning: "татгалзах", pos: "Үйл үг", exampleKo: "부당한 지시를 단호하게 거부했습니다.", exampleMn: "Шударга бус шийдвэрээс эрс татгалзсан." },
  { id: 237, level: 5, word: "만족하다", pronunciation: "manjokhada", meaning: "сэтгэл ханах", pos: "Үйл үг", exampleKo: "현재 삶에 깊이 만족하며 살아갑니다.", exampleMn: "Одоогийн амьдралдаа сэтгэл хангалуун амьдарч байна." },
  { id: 238, level: 5, word: "불만족스럽다", pronunciation: "bulmanjokseureopda", meaning: "сэтгэл ханамжгүй", pos: "Тэмдэг нэр", exampleKo: "부당한 거래 조건이 매우 불만족스럽습니다.", exampleMn: "Шударга бус арилжааны нөхцөл байдал үнэхээр сэтгэл ханамжгүй байна." },
  { id: 239, level: 5, word: "효율적이다", pronunciation: "hyoyuljeogida", meaning: "үр ашигтай", pos: "Тэмдэг нэр", exampleKo: "이 자원 개발은 대단히 효율적이다.", exampleMn: "Энэхүү нөөцийг хөгжүүлэх нь маш үр ашигтай." },
  { id: 240, level: 5, word: "적극적이다", pronunciation: "jeokgeukjeogida", meaning: "идэвхтэй", pos: "Тэмдэг нэр", exampleKo: "매사에 배우려는 적극적인 자세가 보인다.", exampleMn: "Алив зүйлд суралцах гэсэн идэвхтэй хандлага нь харагдаж байна." },
  { id: 241, level: 5, word: "소극적이다", pronunciation: "sogeukjeogida", meaning: "идэвхгүй", pos: "Тэмдэг нэр", exampleKo: "문제를 대하는 소극적인 성격을 고쳤다.", exampleMn: "Асуудалд хандах идэвхгүй зан чанараа зассан." },
  { id: 242, level: 5, word: "필수적이다", pronunciation: "pilsujeogida", meaning: "зайлшгүй хэрэгтэй", pos: "Тэмдэг нэр", exampleKo: "꾸준한 복습은 시험에 필수적입니다.", exampleMn: "Тогтмол давтах нь шалгалтанд зайлшгүй хэрэгтэй." },
  { id: 243, level: 5, word: "안정적이다", pronunciation: "anjeongjeogida", meaning: "тогтвортой", pos: "Тэмдэг нэр", exampleKo: "정치적 기반이 아주 안정적입니다.", exampleMn: "Улс төрийн суурь маш тогтвортой байна." },
  { id: 244, level: 5, word: "지속적이다", pronunciation: "jisojeogida", meaning: "үргэлжилсэн (тасралтгүй)", pos: "Тэмдэг нэр", exampleKo: "환경보호를 위한 지속적인 투자가 요구된다.", exampleMn: "Байгаль орчныг хамгаалах тасралтгүй хөрөнгө оруулалт шаардлагатай." },
  { id: 245, level: 5, word: "전문적이다", pronunciation: "jeonmunjeogida", meaning: "мэргэжлийн", pos: "Тэмдэг нэр", exampleKo: "해당 보고서는 대단히 전문적이다.", exampleMn: "Энэхүү тайлан нь маш мэргэжлийн түвшнийх байна." },
  { id: 246, level: 5, word: "구체적이다", pronunciation: "guchejeogida", meaning: "тодорхой", pos: "Тэмдэг нэр", exampleKo: "실행 방안을 보다 구체적으로 밝혀라.", exampleMn: "Хэрэгжүүлэх арга замаа илүү тодорхой болго." },
  { id: 247, level: 5, word: "일반적이다", pronunciation: "ilbanjeogida", meaning: "ерөнхий (түгээмэл)", pos: "Тэмдэг нэр", exampleKo: "이 현상은 아주 일반적인 사회 변화다.", exampleMn: "Энэ үзэгдэл бол маш түгээмэл нийгмийн өөрчлөлт." },
  { id: 248, level: 5, word: "현실적이다", pronunciation: "hyeonsiljeogida", meaning: "бодитой (реалист)", pos: "Тэмдэг нэр", exampleKo: "실행 가능하고 현실적인 목표를 세워요.", exampleMn: "Хэрэгжиж болохуйц бодитой зорилго тавь." },
  { id: 249, level: 5, word: "이상적이다", pronunciation: "isangjeogida", meaning: "төгс/идеал", pos: "Тэмдэг нэр", exampleKo: "이 장소는 야외 콘서트에 아주 이상적입니다.", exampleMn: "Энэ газар гадаа тоглолт хийхэд үнэхээр төгс тохирно." },
  { id: 250, level: 5, word: "대표적이다", pronunciation: "daepyojeogida", meaning: "төлөөлөхүйц", pos: "Тэмдэг нэр", exampleKo: "이 작품은 작가의 가장 대표적인 성과물이다.", exampleMn: "Энэ бүтээл бол зохиолчийн хамгийн төлөөлөхүйц ололт амжилт." },

  // ================= LEVEL 6 (251 - 300) =================
  { id: 251, level: 6, word: "본질", pronunciation: "bonjil", meaning: "мөн чанар", pos: "Нэр үг", exampleKo: "문제의 본질을 정확히 파악해야 한다.", exampleMn: "Асуудлын мөн чанарыг зөв ойлгож мэдэх хэрэгтэй." },
  { id: 252, level: 6, word: "관점", pronunciation: "gwanjeom", meaning: "өнцөг/үзэл бодол", pos: "Нэр үг", exampleKo: "다른 사람의 관점에서도 생각해 봅시다.", exampleMn: "Бусад хүний өнцгөөс ч гэсэн бодож үзэцгээе." },
  { id: 253, level: 6, word: "논리", pronunciation: "nonri", meaning: "логик", pos: "Нэр үг", exampleKo: "그의 주장에는 일관된 논리가 부족하다.", exampleMn: "Түүний шаардлагад тууштай логик дутагдаж байна." },
  { id: 254, level: 6, word: "추세", pronunciation: "chuse", meaning: "чиг хандлага", pos: "Нэр үг", exampleKo: "최근 물가가 급상승하는 추세에 있습니다.", exampleMn: "Сүүлийн үед барааны үнэ хурдан өсөх чиг хандлагатай байна." },
  { id: 255, level: 6, word: "현황", pronunciation: "hyeonhwang", meaning: "өнөөгийн байдал", pos: "Нэр үг", exampleKo: "현재 수출입 현황 보고서를 작성했습니다.", exampleMn: "Одоогийн экспорт импортын байдлын тайланг гаргасан." },
  { id: 256, level: 6, word: "쟁점", pronunciation: "jaengjeom", meaning: "маргаантай асуудал", pos: "Нэр үг", exampleKo: "회의에서 뜨거운 쟁점이 논의되었습니다.", exampleMn: "Хурлаар маш халуун маргаантай асуудлыг хэлэлцсэн." },
  { id: 257, level: 6, word: "잠재력", pronunciation: "jamjaeryeok", meaning: "нөөц боломж (чадавхи)", pos: "Нэр үг", exampleKo: "그는 무한한 잠재력을 가진 학생입니다.", exampleMn: "Тэр бол хязгааргүй нөөц боломж/чадавхитай сурагч." },
  { id: 258, level: 6, word: "혁신", pronunciation: "hyeoksin", meaning: "инноваци (шинэчлэл)", pos: "Нэр үг", exampleKo: "기술 혁신을 선도하는 기업으로 성장했다.", exampleMn: "Технологийн инновациар түүчээлэгч компани болон өслөө." },
  { id: 259, level: 6, word: "지속가능성", pronunciation: "jisogganeungseong", meaning: "тогтвортой байдал", pos: "Нэр үг", exampleKo: "이 정책은 환경의 지속가능성을 고려했다.", exampleMn: "Энэ бодлого байгаль орчны тогтвортой байдлыг тооцсон." },
  { id: 260, level: 6, word: "세계화", pronunciation: "segyehwa", meaning: "даяаршил", pos: "Нэр үг", exampleKo: "오늘날 세계화 시대에 발맞춰 나가야 한다.", exampleMn: "Өнөөгийн даяаршлын эринтэй мөр зэрэгцэн алхах хэрэгтэй." },
  { id: 261, level: 6, word: "전문성", pronunciation: "jeonmunseong", meaning: "мэргэжлийн ур чадвар", pos: "Нэр үг", exampleKo: "업무의 전문성을 기르기 위해 훈련했다.", exampleMn: "Ажлын мэргэжлийн ур чадварыг хөгжүүлэхээр бэлтгэл хийсэн." },
  { id: 262, level: 6, word: "다양성", pronunciation: "dayangseong", meaning: "олон янз байдал", pos: "Нэр үг", exampleKo: "문화의 다양성을 깊이 존중해야 합니다.", exampleMn: "Соёлын олон янз байдлыг гүнээ хүндэтгэх ёстой." },
  { id: 263, level: 6, word: "고정관념", pronunciation: "gojonggwannyeom", meaning: "хэвшмэл ойлголт", pos: "Нэр үг", exampleKo: "직업에 대한 고정관념을 타파해야 한다.", exampleMn: "Ажил мэргэжлийн талаарх хэвшмэл ойлголтыг өөрчлөх хэрэгтэй." },
  { id: 264, level: 6, word: "상호작용", pronunciation: "sanghojakyong", meaning: "харилцан үйлчлэл", pos: "Нэр үг", exampleKo: "교사와 학생 간의 활발한 상호작용이 중요하다.", exampleMn: "Багш сурагч хоорондын идэвхтэй харилцан үйлчлэл чухал." },
  { id: 265, level: 6, word: "자율성", pronunciation: "jayulseong", meaning: "бие даасан байдал", pos: "Нэр үг", exampleKo: "학생들의 학업 자율성을 적극 보장한다.", exampleMn: "Оюутнуудын бие даан суралцах байдлыг идэвхтэй хангадаг." },
  { id: 266, level: 6, word: "효율성", pronunciation: "hyoyulseong", meaning: "үр ашиг", pos: "Нэр үг", exampleKo: "에너지 이용 효율성을 높여야 합니다.", exampleMn: "Эрчим хүчний ашиглалтын үр ашгийг дээшлүүлэх ёстой." },
  { id: 267, level: 6, word: "타당성", pronunciation: "tadangseong", meaning: "үндэслэлтэй байдал", pos: "Нэр үг", exampleKo: "이 계획의 타당성을 꼼꼼히 검토했다.", exampleMn: "Энэхүү төлөвлөгөөний үндэслэлтэй байдлыг нарийвчлан хянасан." },
  { id: 268, level: 6, word: "우선순위", pronunciation: "useonsunwi", meaning: "тэргүүлэх чиглэл", pos: "Нэр үг", exampleKo: "가장 급한 일에 우선순위를 둡니다.", exampleMn: "Хамгийн яаралтай ажилд тэргүүлэх чиглэл өгнө." },
  { id: 269, level: 6, word: "해결책", pronunciation: "haegyeolchaek", meaning: "шийдэл", pos: "Нэр үг", exampleKo: "근본적인 곤경의 해결책을 모색하고 있다.", exampleMn: "Үндсэн хүндрэлийг шийдэх шийдлийг хайж байна." },
  { id: 270, level: 6, word: "접근법", pronunciation: "jeopgeunbeop", meaning: "хандлага/арга барил", pos: "Нэр үг", exampleKo: "문제에 대한 새로운 접근법이 통했다.", exampleMn: "Асуудалд хандах шинэ арга барил үр дүнгээ өглөө." },
  { id: 271, level: 6, word: "시사하다", pronunciation: "sisahada", meaning: "илтгэх (сануулах)", pos: "Үйл үг", exampleKo: "이 조사는 시사하는 바가 대단히 큽니다.", exampleMn: "Энэхүү судалгааны илтгэж/сануулж буй зүйл маш их." },
  { id: 272, level: 6, word: "반영하다", pronunciation: "banyeonghada", meaning: "тусгах", pos: "Үйл үг", exampleKo: "소비자의 기호를 즉각 정책에 반영했다.", exampleMn: "Хэрэглэгчийн таашаалыг бодлогодоо шууд тусгасан." },
  { id: 273, level: 6, word: "유도하다", pronunciation: "yudohada", meaning: "өдөөх (чиглүүлэх)", pos: "Үйл үг", exampleKo: "대화 참여를 자연스럽게 유도했다.", exampleMn: "Харилцаанд оролцох байдлыг нь аяндаа өдөөж өгсөн." },
  { id: 274, level: 6, word: "입증하다", pronunciation: "ipjeonghada", meaning: "нотлох", pos: "Үйл үг", exampleKo: "실험 결과를 과학적으로 입증했습니다.", exampleMn: "Туршилтын үр дүнг шинжлэх ухааны үндэслэлтэй нотолсон." },
  { id: 275, level: 6, word: "규제하다", pronunciation: "gyujehada", meaning: "зохицуулах (хязгаарлах)", pos: "Үйл үг", exampleKo: "불법적인 상거래 행위를 엄격히 규제했다.", exampleMn: "Хууль бус арилжаа хийх явцыг хатуу зохицуулсан." },
  { id: 276, level: 6, word: "완화하다", pronunciation: "wanhwahada", meaning: "зөөлрүүлэх (сулруулах)", pos: "Үйл үг", exampleKo: "외국인 투자 제한 법안을 대폭 완화했다.", exampleMn: "Гадаадын хөрөнгө оруулалтын хязгаарлалтын хуулийг ихээхэн зөөлрүүлсэн." },
  { id: 277, level: 6, word: "확보하다", pronunciation: "hwakbohada", meaning: "баталгаажуулах (олж авах)", pos: "Үйл үг", exampleKo: "재정적 예산을 안정적으로 확보했습니다.", exampleMn: "Санхүүгийн төсвөө тогтвортойгоор баталгаажуулж авсан." },
  { id: 278, level: 6, word: "촉구하다", pronunciation: "chokguhada", meaning: "шаардах/уриалах", pos: "Үйл үг", exampleKo: "개혁안 통과를 적극적으로 촉구했다.", exampleMn: "Шинэчлэлийн хууль батлагдахыг идэвхтэй шаардлаа." },
  { id: 279, level: 6, word: "제시하다", pronunciation: "jesihada", meaning: "дэвшүүлэх (үзүүлэх)", pos: "Үйл үг", exampleKo: "해결을 위한 유망한 대안을 제시했다.", exampleMn: "Шийдвэрлэхийн тулд ирээдүйтэй хувилбар дэвшүүлсэн." },
  { id: 280, level: 6, word: "수용하다", pronunciation: "suyonghada", meaning: "хүлээн авах", pos: "Үйл үг", exampleKo: "타인의 정당한 건의사항을 흔쾌히 수용했다.", exampleMn: "Бусдын зүй ёсны саналыг дуртайяа хүлээн авсан." },
  { id: 281, level: 6, word: "대처하다", pronunciation: "daecheohada", meaning: "арга хэмжээ авах", pos: "Үйл үг", exampleKo: "위기 사태에 슬기롭게 대처하였습니다.", exampleMn: "Хямралын үед ухаалгаар арга хэмжээ авсан." },
  { id: 282, level: 6, word: "부각되다", pronunciation: "bugakdweda", meaning: "тодрон гарах", pos: "Үйл үг", exampleKo: "문화 교류의 가치가 요즘 더 부각되고 있다.", exampleMn: "Соёлын солилцооны үнэ цэнэ сүүлийн үед улам тодрон гарч байна." },
  { id: 283, level: 6, word: "초래하다", pronunciation: "choraehada", meaning: "дагуулах (дагуулж ирэх)", pos: "Үйл үг", exampleKo: "무분별한 벌목은 산사태를 초래한다.", exampleMn: "Замбараагүй мод тайрах нь хөрсний нуралт дагуулдаг." },
  { id: 284, level: 6, word: "기인하다", pronunciation: "giinhada", meaning: "улбаалах (үүдэн гарах)", pos: "Үйл үг", exampleKo: "이번 실패는 소통 부족에서 기인했다.", exampleMn: "Энэ удаагийн бүтэлгүйтэл харилцаа дутагдсанаас улбаалсан." },
  { id: 285, level: 6, word: "간과하다", pronunciation: "gangwahada", meaning: "үл тоомсорлох (алгасах)", pos: "Үйл үг", exampleKo: "기초적인 사실을 절대 간과해서는 안 된다.", exampleMn: "Суурь баримтуудыг хэзээ ч үл тоомсорлож/алгасаж болохгүй." },
  { id: 286, level: 6, word: "내포하다", pronunciation: "naepohada", meaning: "агуулах", pos: "Үйл үг", exampleKo: "그 언사에는 깊은 의미를 내포하고 있다.", exampleMn: "Тэр ярианд маш гүн утга агуулагдаж байна." },
  { id: 287, level: 6, word: "전환되다", pronunciation: "jeonhwandweda", meaning: "шилжих", pos: "Үйл үг", exampleKo: "자동화 시스템으로 전면 전환되었습니다.", exampleMn: "Автоматжуулсан систем рүү бүрэн шилжсэн." },
  { id: 288, level: 6, word: "분배하다", pronunciation: "bunbaehada", meaning: "хуваарилах", pos: "Үйл үг", exampleKo: "이익을 주주들에게 정당하게 분배했다.", exampleMn: "Ашгийг хувьцаа эзэмшигчдэд шударгаар хуваарилсан." },
  { id: 289, level: 6, word: "통합하다", pronunciation: "tonghabhada", meaning: "нэгтгэх", pos: "Үйл үг", exampleKo: "두 부서를 하나로 긴밀히 통합했다.", exampleMn: "Хоёр хэлтсийг нэг болгон нягт нэгтгэлээ." },
  { id: 290, level: 6, word: "확대하다", pronunciation: "hwagdaehada", meaning: "өргөжүүлэх", pos: "Үйл үг", exampleKo: "지원 대상을 점차 확대하고 있습니다.", exampleMn: "Дэмжих хамрах хүрээгээ аажмаар өргөжүүлж байна." },
  { id: 291, level: 6, word: "위축되다", pronunciation: "wichukdweda", meaning: "агших (буурах)", pos: "Үйл үг", exampleKo: "소비 심리가 급격하게 위축되었습니다.", exampleMn: "Хэрэглээний сэтгэл зүй маш хурдан агшсан/буурсан." },
  { id: 292, level: 6, word: "왜곡되다", pronunciation: "waegokdweda", meaning: "гажуудах (буруу илэрхийлэгдэх)", pos: "Үйл үг", exampleKo: "역사적 사실이 왜곡되어서는 절대 안 된다.", exampleMn: "Түүхэн бодит үнэн гажуудаж хэзээ ч болохгүй." },
  { id: 293, level: 6, word: "도출하다", pronunciation: "dochulhada", meaning: "гаргаж авах", pos: "Үйл үг", exampleKo: "장시간 협상 끝에 결론을 도출해 냈다.", exampleMn: "Удаан хугацааны яриа хэлэлцээний эцэст шийдлийг гаргаж авлаа." },
  { id: 294, level: 6, word: "시급하다", pronunciation: "sigeuphada", meaning: "яаралтай", pos: "Тэмдэг нэр", exampleKo: "재해 지역의 구호가 대단히 시급합니다.", exampleMn: "Гамшгийн бүс нутагт тусламж үзүүлэх нь маш яаралтай." },
  { id: 295, level: 6, word: "현저하다", pronunciation: "hyeonjeohada", meaning: "мэдэгдэхүйц", pos: "Тэмдэг нэр", exampleKo: "지난달에 비해 소득 증가율이 현저하다.", exampleMn: "Өнгөрсөн сартай харьцуулахад орлогын нэмэгдэл мэдэгдэхүйц байна." },
  { id: 296, level: 6, word: "불가피하다", pronunciation: "bulgapihada", meaning: "зайлшгүй", pos: "Тэмдэг нэр", exampleKo: "계획의 일부 수정은 이제 불가피합니다.", exampleMn: "Төлөвлөгөөнд зарим өөрчлөлт оруулах нь одоо зайлшгүй болсон." },
  { id: 297, level: 6, word: "모호하다", pronunciation: "mohohada", meaning: "тодорхой бус", pos: "Тэмдэг нэр", exampleKo: "규정의 문구가 지나치게 모호합니다.", exampleMn: "Дүрмийн үг хэллэг хэтэрхий тодорхой бус байна." },
  { id: 298, level: 6, word: "객관적이다", pronunciation: "gaegwanjeogida", meaning: "бодитой/объектив", pos: "Тэмдэг нэр", exampleKo: "상황을 객관적으로 분석해야 합니다.", exampleMn: "Нөхцөл байдалд объектив дүн шинжилгээ хийх ёстой." },
  { id: 299, level: 6, word: "주관적이다", pronunciation: "jugwanjeogida", meaning: "субъектив", pos: "Тэмдэг нэр", exampleKo: "아름다움에 대한 평가는 주관적이다.", exampleMn: "Үзэсгэлэнтэй байдлын үнэлгээ нь субъектив байдаг." },
  { id: 300, level: 6, word: "궁극적이다", pronunciation: "gunggeukjeogida", meaning: "эцсийн, туйлын", pos: "Тэмдэг нэр", exampleKo: "우리 연구의 궁극적인 목표에 도달했다.", exampleMn: "Манай судалгааны эцсийн туйлын зорилтод хүрлээ." }
];

// Export if module environment, otherwise let it exist globally in browser
if (typeof module !== 'undefined' && module.exports) {
  module.exports = KQUEST_WORDS;
}
